### ISSUE TITLE
Access Express App from within Route

### ISSUE THREAD

**Issue by sarus** [anotheri/express-routescan#3]
Do you have any recommended ways to pass in parameters to the routes from the main express application.  For example, if my route files need access to the http server object is there a good way to give the route files themselves access to that?  Thanks!

**Comment by anotheri** [comment]
I've not implemented passing extra parameters such as `app` and other into the routes’ initialization because of you can get access to express application by using `req.app`.

For example, if we use standard generated Express application, add some extra lines in next files after installation `express-routescan` node module:

``` javascript
// myapp/app.js

var express = require( 'express' );
var routescan = require( 'express-routescan' );
// ...
var app = express();
// ...

app.set( 'name', 'My awesome app' );

routescan( app );
//...
```

``` javascript
// myapp/routes/index.js

'use strict';

/* GET home page. */

module.exports = {

    '/': function( req, res ){
        var app = req.app; // ← It is your express application!
        res.render( 'index', { 
            title: app.get( 'name' )
        } );
    }

};
```

This example is showing how to get express application object inside the route and how to pass extra parameters by using `app.set( … )` and `app.get( … )` methods. And obviously as well as strings: `app.set( 'myString', 'My lovely string' );` you can pass everything:
- objects: `app.set( 'myObj', { "a": 1, "b": "two", /* … */ } );`,
- arrays: `app.set( 'myArr', [ 1, 2, 3, /* … */ ] );`
- so on.

**Comment by sarus** [comment]
Thank you for the information.  I didn't realize you can just access `app` from `req` so that is definitely useful.  I can add any modules that are required in the routes to the app object and then access them from req which is working.

Thank you again!

**Comment by anotheri** [comment]
You're welcome!
